### ISSUE TITLE
Making :enter-chain more convenient

### ISSUE THREAD

**Issue by jkarni** [radicle-dev/radicle#197]
`:enter-chain` worked more or less nicely so far, but chains are moving towards requiring signatures and uuids. The chain being entered can't provide convenience functions for these, so it is becoming hard to actually send any expression to be evaluated.

One possible fix is to `:enter-chain-with <chain> <vec of identifiers>`, where these new identifiers are *also* available in the new env. Crucially, expressions would need to be evaled in two steps: *first*, the identifiers (or their application); *then* the remainder of the expression (so that what's stored as an input to be sent to the chain does not contain the additional identifiers). This seems subtle and confusing.

The other option is to have something like unquoting, which would allow certain expressions to be evaled before, and in the surrounding env.

**Comment by jameshaydon** [comment]
`:enter-chain` no longer exists.
