### ISSUE TITLE
Catch exceptions in Radicle tests

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle#274]
The testing functions `run-test` in `rad/prelude/tests.rad` should catch exception thrown in the test case and setup code. If an exception is thrown the test should be marked as failed and the stack trace printed.

**Comment by maxhallinan** [comment]
Is this still an issue? It seems like it's not but maybe I misunderstood. 

For example:

```
(load! (find-module-file! "prelude.rad"))
(import prelude/test)

(def tests (ref []))

(def foo
  (fn [x]
    (throw 'foo "foo bar baz")))

(:test "foo"
 [(foo #t) ==> #t])

(:test "bar"
 [(eq? #t #t) ==> #t])

(prelude/test/run-all (read-ref tests))
```

has this output

```
1..2
not ok 1 - foo
"foo bar baz"
ok 2 - bar
```

The exception is caught and the message printed, and the test suite does not crash.

**Comment by geigerzaehler** [comment]
You’re right @maxhallinan. This was fixed a while ago. Closing.
