### ISSUE TITLE
Interactive docs

### ISSUE THREAD

**Issue by jameshaydon** [radicle-dev/radicle#282]
Since we have GHCJS we might as well have nice interactive docs, editable examples, etc.

**Comment by hxrts** [comment]
+1

I think there are some really interesting ways we could play with interactive docs that work both in the browser & CLI context, particularly if the system is eventually open to crowdsourcing.

Posted this in IRC recently, but adding here for reference:

https://gist.github.com/oakes/8db57ac808bf6ec144d627fd83a89da3

**Comment by jameshaydon** [comment]
We do not support GHCJS anymore.
