### ISSUE TITLE
RFC: Module search path

### ISSUE THREAD

**Issue by jkarni** [radicle-dev/radicle#294]
In order to make `radicle` (in particular scripts written with it) usable anywhere, it would be good to have a search path for modules. We can then install `prelude` et al. in the default search path, and those scripts can use it.

Suggested offline is using the usual env variable (e.g. `RAD_PATH`). During development we can set `RAD_PATH` to be the path to this repo's `rad` dir, and so don't need to reinstall.

**Comment by jameshaydon** [comment]
Done in #397.
