### ISSUE TITLE
Always decode source files with UTF-8

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle#312]
We should always decode radicle source files as UTF-8 so that the following example works
~~~
echo ";;☺\n:ok" | LC_ALL=C radicle -
~~~

To accomplish this `readFileS` should use `Data.ByteString.readFile` and `Data.Text.Encoding.decodeUtf8`. See also [“Beware of readFile”](https://www.snoyman.com/blog/2016/12/beware-of-readfile).

**Comment by maxhallinan** [comment]
@geigerzaehler this is fixed by #327 :)

**Comment by geigerzaehler** [comment]
😎 🎉
