### ISSUE TITLE
Distribute non-Haskell binaries as part of Cabal package

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle#331]
There is a good chance we will have non-Haskell binaries that we want to distribute with Radicle. The easiest would be to distribute them with the Cabal package. For this we would need to customize `Setup.hs` to install the binaries.

**Comment by xla** [comment]
@geigerzaehler Hej looked into that earlier with @cloudhead. Could you give examples of such binaries we want to distribute through the haskell toolchain?

**Comment by geigerzaehler** [comment]
Right now I’m using a bash script wrap the IPFS daemon for Radicle in my development work. This is something that we will likely also ship to the user.

**Comment by cloudhead** [comment]
The end user won't be installing radicle through stack/cabal though, so I'm not sure this is necessary - eg. database clients don't ship with the database binary.

**Comment by geigerzaehler** [comment]
This is done now
