### ISSUE TITLE
Incorrectly spelled command in "Contribute to Radicle Garden" section of documentation

### ISSUE THREAD

**Issue by urcades** [radicle-dev/radicle#548]
Hi! In the following section, there is a mismatch in the commands being specified.

Specifically, `$ rad issue show 1` should be `$ rad issue show 0`.

<img width="945" alt="Screen Shot 2019-03-13 at 02 17 02" src="https://user-images.githubusercontent.com/1195363/54257645-5ea60580-4536-11e9-92c8-9dff0a170848.png">

This can be found here: http://www.radicle.xyz/docs/#installation-setup

**Comment by geigerzaehler** [comment]
Thanks for the feedback @urcades. @jameshaydon fixed the docs
