### ISSUE TITLE
Error on `rad patch list`

### ISSUE THREAD

**Issue by zenhack** [radicle-dev/radicle#559]
A few hours ago I went through part 1 of the tutorial, and submitted a patch with a new garden via radicle. I came back to check on the status, typed `rad patch list`, and got this:

```
Invalid radicle input:
  machine-id: 12D3KooWAmB1gB9kceaGfKaUHfhcmfUzXdJEbzRnT73mF1DrknSk
  radicle-error: Exception validation-failure {:info "Did not satisfy predicate."
:name "edit author == original author"}
  src/Radicle/Internal/PrimFns.hs:165:32 throwErrorHere
[ipfs]:159:12
[ipfs]:159:13
[ipfs]:92:2
[ipfs]:93:3
[ipfs]:48:3
[ipfs]:7:2
[ipfs]:107:5
src/Radicle/Internal/Core.hs:351:12 annotate
src/Radicle/Internal/PrimFns.hs:154:16 List
[ipfs]:32:6
[ipfs]:32:7
[ipfs]:118:3
[ipfs]:71:6
[ipfs]:71:7
[ipfs]:75:7
src/Radicle/Internal/Core.hs:386:26 annotate
src/Radicle/Internal/Eval.hs:65:23 Lambda
```

I'm using commit ba9ef05402dc8dd2223a4b9c996faa341dc76653, built with stack. `rad issue list` seems to work fine.

The commit hash of the patch I submitted was `6c6e30a5bf152997d14508b37910ddd7f3635416`.

Let me know if there's any other useful information I can provide.

**Comment by MeBrei** [comment]
Thank you for reporting the issue! 
The error comes from an unauthorised patch edit that was sent to the machine. This should have been prevented by on-machine validations. We fixed the the bug and are currently working on updating the machine. After that you should be able to propose your patch without problems. 

I will let you know once we made the upgrade.

**Comment by jameshaydon** [comment]
@zenhack Can you confirm this is now working for you? (You may need to restart `daemon-radicle`.)

**Comment by zenhack** [comment]
@jameshaydon, yep, seems to be working.
