### ISSUE TITLE
cabal file for build outside stack?

### ISSUE THREAD

**Issue by shapr** [radicle-dev/radicle#566]
Hello, I'm really excited about radicle!

I was instantly able to build and use git-remote-ipfs, but I'm not able to build radicle from `hpack && cabal new-install all`

There's an error with a missing Applicative instance in `ipfsHttpPost'` and I'm not able to figure it out with a few minutes of digging.

Would it be convenient to include a cabal file with package bounds?

Thanks,

**Comment by kim** [comment]
Hey @shapr, not _exactly_ convenient, as the workflow over here is somewhat tied to stack ;) 

But maybe as a stop-gap solution you could just download https://www.stackage.org/lts-13.10/cabal.config to the project directory and see how that goes? You may still need to tweak some version bounds for the non-stackage dependencies and create a cabal.project to pull the ipfs git dependency (works with latest `cabal`).
