### ISSUE TITLE
Follow up on PR #617

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle#619]
PR #617  fixed a problem reported in #587 . This should be followed by:

- [x] updating the documentation of `nonAtomicRead`
- [x] in `ensureMachineLoaded` make `writeMachineConfig` conditional (before it was only run on case `Nothing`
- [x] ensure that the test catch this kind of problem. Since we test creating and checking out projects on the same radicle daemon, the machine.json is never empty on `rad project checkout`. Tests should run multiple radicle daemons acting as reader and writers.

**Comment by jameshaydon** [comment]
Done in #621 and #624.
