### ISSUE TITLE
How can I uninstall `radicle`?

### ISSUE THREAD

**Issue by NabiKAZ** [radicle-dev/radicle#633]
How can I uninstall `radicle`?

**Comment by jkarni** [comment]
That depends on how you installed it:

- `brew uninstall radicle-alpha` for mac
- `apt-get remove radicle` for deb
-  `rm ~/.local/bin/radicle* && rm ~/.local/bin/rad && rm ~/.local/bin/rad-daemon-radicle && rm -rf ~/.local/share/radicle  && rm -rf ~/.config/radicle` for stack installation with default XDG paths

Let me know if that works!

**Comment by jameshaydon** [comment]
@NabiKAZ Yes that would correspond to the last bullet-point.

**Comment by jkarni** [comment]
@NabiKAZ closing, but feel free to reopen or comment if you have more questions.
