### ISSUE TITLE
Federation with ForgeFed

### ISSUE THREAD

**Issue by dcarroll9999** [radicle-dev/radicle#672]
[ForgeFed](https://notabug.org/peers/forgefed) is a protocol attempting to federate git forges with ActivityPub. If radicle was federated, it will provide a UX interface along with hopefully speeding up adoption, and allowing users to fork to radicle and directly submit a PR to a git repo on another forge.
Thanks for this great program.

**Comment by hoijui** [comment]
I very much like the iade of an open, very flexible protocol to bring projects like this together. I ask myself though, why they chose a decentralized over a distributed workflow. it is like.. going one step in the right direction instead of going two rigth away.

**Comment by dcarroll9999** [comment]
What do you mean? It's just a universal way for users to communicate

**Comment by dcarroll9999** [comment]
What do you mean? It's just a universal way for users to communicate

**Comment by hoijui** [comment]
nope, it is federated==decentralized, which is inbetween centralized and distributed.

see [this explanation](https://medium.com/distributed-economy/what-is-the-difference-between-decentralized-and-distributed-systems-f4190a5c6462).

**Comment by kim** [comment]
While interesting in theory, federated protocols come with their own drawbacks -- the biggest one being that actors in a federated network each have their own interests and incentives. Moxie Marlinspike wrote an interesting [piece](https://signal.org/blog/the-ecosystem-is-moving/) on the topic a while back.

We are fans of the "Fediverse", but the truth is that ForgeFed never took off, perhaps for some of the reasons Moxie laments. We'll see, maybe at some point it gets enough traction, in which case we'll consider ways to support it.
