### ISSUE TITLE
A more approachable issue format

### ISSUE THREAD

**Issue by expenses** [radicle-dev/radicle#694]
Hi, not sure if I should make this issue here or inside radicle itself.
```
;; Issue template. An empty or invalid value will abort.
{:title      "Pick a title"
 :body       "Pick a body"
 :labels     []
}
```

The issue format at the moment is not super approachable for people who aren't familiar with haskell. I think the best solution to this would be to have the issue format in markdown with some additional metadata, [like Jekyll posts](https://jekyllrb.com/docs/posts/#creating-posts). Then the above becomes:
```
---
title: <title>
tags: [<tags>]
---

...
```

Or, perhaps:

```
# <title>

<body>

---
<tags>
```

**Comment by FintanH** [comment]
Hey @expenses, a lot of the work for code collaboration has moved over to [radicle-link](https://github.com/radicle-dev/radicle-link). Issues are on our roadmap in the next 4 months, so we'll be working out formats during the research phase and how/where they'll be structured. If you keep an eye out in `radicle-link`, [radicle-upstream](https://github.com/radicle-dev/radicle-upstream) (our application code), and the [discourse](https://radicle.community/) we'd love to get your thoughts and input during the discussions :)

**Comment by expenses** [comment]
Oh, ok. Might make sense to add a link in the repo description to https://github.com/radicle-dev/radicle-link then.
